---
- name: "Installing apache webserver to webservers"
  hosts: webservers
  user: ansible
  become: yes
  tasks:
    - name: install apache
      yum: 
        name: httpd
        state: present

    - name: Copy a "webcontent" folder on the remote machines 
      become: yes
      copy: 
        src: /home/ansible/Ansible/webcontent/
        dest: /var/www/html/
            

    - name: Set Document Root for apache
      set_fact: 
        doc_root: "/var/www/html/webcontent"    
  
    - name: Add firewall rule
      firewalld: 
        state: enabled
        service: http
        permanent: yes
      
    
    - name: Start and enable a service
      service:
        name: httpd
        state: started
        enabled: yes
